### ISSUE TITLE
Install fails. 

### ISSUE THREAD

**Issue by siedentop** [bitly/pyqrencode#1]
Using easy_install the installation fails. See below for details. 
I'll provide more information if needed. 

$ sudo easy_install pyqrencode
install_dir /usr/local/lib/python2.6/dist-packages/
Searching for pyqrencode
Reading http://pypi.python.org/simple/pyqrencode/
Reading http://github.com/bitly/pyqrencode
Best match: pyqrencode 0.2
Downloading http://github.com/downloads/bitly/pyqrencode/pyqrencode-0.2.tar.gz
Processing pyqrencode-0.2.tar.gz
Running pyqrencode-0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-sG0j_d/pyqrencode-0.2/egg-dist-tmp-U7FsdT
qrencode.c:4: fatal error: Python.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by mreiferson** [comment]
Looks like you don't have python development libraries installed.

**Comment by siedentop** [comment]
With python-dev and python-all-dev (in Ubuntu 10.10) installed the error changes thus: 

Running pyqrencode-0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-Tz_7Ki/pyqrencode-0.2/egg-dist-tmp-a5Hm4G
qrencode.c:199: fatal error: qrencode.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1

**Comment by mreiferson** [comment]
you need libqrencode installed as well

**Comment by siedentop** [comment]
libqrencode-dev (again in Ubuntu repositories) helps. 

This is solved now, but I would strongly recommend to make the pip package slightly smarter. At least tell me about dependencies if the build fails...
